
package editor;
import java.awt.Color;
import java.lang.Math;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Hashtable;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.undo.UndoManager;

/**
 *
 * @author Erick Daniel Paredes
 */

public class bloc extends javax.swing.JFrame {

    protected UndoManager undoManager = new UndoManager();
    
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de texto (*.txt)", "txt");
    
    boolean estado = false;
    String ruta = "";
    String titulo = "Quantum";
    int longitud;
    int row;

    
    static JFileChooser file = new JFileChooser();
    static File fichero;
    static String texto;
    static int seleccion;
    static BufferedReader reader = null;
    
    public bloc() {
        initComponents();
        setLocationRelativeTo(null);
        
         Text1.setLineWrap(true);
        estado = false;
        Text1.getDocument().addUndoableEditListener(
                new UndoableEditListener() {

                    @Override
                    public void undoableEditHappened(UndoableEditEvent e) {
                        undoManager.addEdit(e.getEdit());
                    }
                }
        );
        
        
        
    }

    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Text1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Text2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Text3 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Negrita = new javax.swing.JMenuItem();
        Cursiva = new javax.swing.JMenuItem();
        Subrayado = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Text1.setColumns(20);
        Text1.setRows(5);
        jScrollPane1.setViewportView(Text1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        Text2.setColumns(20);
        Text2.setRows(5);
        jScrollPane2.setViewportView(Text2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        Text3.setColumns(20);
        Text3.setRows(5);
        jScrollPane3.setViewportView(Text3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quantum\\Desktop\\Editor\\build\\classes\\archivos\\iconos\\folder-horizontal-open.png")); // NOI18N
        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quantum\\Desktop\\Editor\\build\\classes\\archivos\\iconos\\disk.png")); // NOI18N
        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quantum\\Desktop\\Editor\\build\\classes\\archivos\\iconos\\saveas.png")); // NOI18N
        jMenuItem3.setText("Guardar como:");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quantum\\Desktop\\Editor\\build\\classes\\archivos\\iconos\\cross-circle.png")); // NOI18N
        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        Negrita.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        Negrita.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quantum\\Desktop\\Editor\\build\\classes\\archivos\\iconos\\office-icon-bold.png")); // NOI18N
        Negrita.setText("Negrita");
        Negrita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NegritaActionPerformed(evt);
            }
        });
        jMenu2.add(Negrita);

        Cursiva.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        Cursiva.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quantum\\Desktop\\Editor\\build\\classes\\archivos\\iconos\\office-icon-italic.png")); // NOI18N
        Cursiva.setText("Cursiva");
        Cursiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursivaActionPerformed(evt);
            }
        });
        jMenu2.add(Cursiva);

        Subrayado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Subrayado.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quantum\\Desktop\\Editor\\build\\classes\\archivos\\iconos\\office-icon-underline.png")); // NOI18N
        Subrayado.setText("Subrayado");
        Subrayado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubrayadoActionPerformed(evt);
            }
        });
        jMenu2.add(Subrayado);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quantum\\Desktop\\Editor\\build\\classes\\archivos\\iconos\\eye.png")); // NOI18N
        jMenuItem8.setText("Visualizar info.");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        guardarComo(); 
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       //creacion del JFrame
       JFrame frame2 = new JFrame("JOptionPane showMessageDialog example");
      // show a joptionpane dialog using showMessageDialog
      JOptionPane.showMessageDialog(frame2,"el editor se esta cerrando");
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void CursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursivaActionPerformed
        if(Text1.isShowing()==true){
     Font f = Text1.getFont(); 
     Text1.setFont(new Font(f.getFontName(),Font.ITALIC,f.getSize()));    
     }
     if(Text2.isShowing()==true){
     Font f = Text2.getFont(); 
     Text2.setFont(new Font(f.getFontName(),Font.ITALIC,f.getSize()));   
     } 
     if(Text3.isShowing()==true){
     Font f = Text3.getFont(); 
     Text3.setFont(new Font(f.getFontName(),Font.ITALIC,f.getSize()));       
     } 
    }//GEN-LAST:event_CursivaActionPerformed

    private void NegritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NegritaActionPerformed
         if(Text1.isShowing()==true){
    Font f = Text1.getFont();
    Text1.setFont(new Font(f.getFontName(),Font.BOLD,f.getSize()));     
    }
    if(Text2.isShowing()==true){
     Font f = Text2.getFont();
    Text2.setFont(new Font(f.getFontName(),Font.BOLD,f.getSize()));     
    }    
    if(Text3.isShowing()==true){
      Font f = Text3.getFont();
      
    Text3.setFont(new Font(f.getFontName(),Font.BOLD,f.getSize()));  
        
        
    }
    }//GEN-LAST:event_NegritaActionPerformed

    private void SubrayadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubrayadoActionPerformed
        System.out.println(Text1.isShowing());
        
        
        if(Text1.isShowing()==true){
        
            
        //JLabel label = new JLabel("Underlined Label");
         
            //Font font = Text1.getFont();
//Font attributes = font.getAttributes();
//font.getFont(font.getFontName(),TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON,font.getSize());
//textField.setFont(font.deriveFont(attributes));
            
        Font f = Text1.getFont();
        System.out.println(TextAttribute.UNDERLINE_ON);
        Hashtable<TextAttribute, Object> map =
            new Hashtable<TextAttribute, Object>();
         map.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
         f = f.deriveFont(map);
        Text1.setFont(f);
        
     }
        
        
        
    }//GEN-LAST:event_SubrayadoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        //*****abrir****
           if (estado == true) {
            int rpta = JOptionPane.showConfirmDialog(this, "Desea guardar los cambios hechos en el documento", "Confirmar", 0);
            if (rpta == 0) {
                guardar();
            } else {
                abrir();
                this.setTitle(": " + titulo);
                longitud = Text1.getText().length();
                System.out.println("Lineas : " + row);
                estado = false;
            }
        } else {
            abrir();
            this.setTitle(": " + titulo);
            longitud = Text1.getText().length();
            System.out.println("Lineas : " + row);
            estado = false;
        } 

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        guardar();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        //****** visualizar
        
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bloc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bloc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bloc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bloc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bloc().setVisible(true);
            }
        });
    }
    //*************** guardar****************************
    public void guardar() {
        try {
            FileWriter fos = new FileWriter(ruta);
            PrintWriter out = new PrintWriter(fos);
            if (out != null) {
                out.println(Text1.getText());
                out.close();
            }
        } catch (IOException e) {
            
        }
    }
    //*****************************guardar como: *****************************
    
    public void guardarComo() {
        file = new JFileChooser();
        file.setFileFilter(filter);
        int opcion = file.showSaveDialog(null);
        File s = null;
        if (opcion == JFileChooser.APPROVE_OPTION) {
            s = file.getSelectedFile();
            try {
                FileWriter fw = new FileWriter(s);
                BufferedWriter bw = new BufferedWriter(fw);
                if (Text1.getText().length() > 0) {
                    fw.write(Text1.getText());
                    ruta = String.valueOf(s);
                }
                fw.close();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error al crear el archivo");
            }
        } else {
            //s = "Operacion Cancelada";
        }
    }
    //*************************** Visualizar********************************
    
    //Aqui hare la instancia del otro jframe
        info obj=new info();
       
    
    
    
   //***************************abrir*********** 
     public void abrir() {
        seleccion = file.showOpenDialog(Text1);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            fichero = file.getSelectedFile();
            ruta = String.valueOf(fichero);
            try {
                reader = new BufferedReader(new FileReader(fichero));
                String lineaTotal = "";
                texto = reader.readLine();
                while (texto != null) {
                    lineaTotal = lineaTotal + texto + System.getProperty("line.separator");
                    texto = reader.readLine();
                }
                Text1.setText(lineaTotal.toString());
                reader.close();
            } catch (Exception e) {
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cursiva;
    private javax.swing.JMenuItem Negrita;
    private javax.swing.JMenuItem Subrayado;
    private javax.swing.JTextArea Text1;
    private javax.swing.JTextArea Text2;
    private javax.swing.JTextArea Text3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
