/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class u4_jni00_EjemploString */

#ifndef _Included_u4_jni00_EjemploString
#define _Included_u4_jni00_EjemploString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     u4_jni00_EjemploString
 * Method:    replaceString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_u4_jni00_EjemploString_replaceString
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
